/**
 * PDF Generation utilities for travel briefs
 */

export interface PDFGenerationOptions {
  title: string;
  html: string;
  filename?: string;
}

/**
 * Generate PDF using browser's print functionality
 * This is the most reliable cross-browser method
 */
export async function generatePDFWithPrint(html: string, filename: string = 'travel-brief.pdf'): Promise<void> {
  return new Promise((resolve, reject) => {
    try {
      // Create a new window for printing
      const printWindow = window.open('', '_blank');
      
      if (!printWindow) {
        reject(new Error('Could not open print window. Please allow popups for this site.'));
        return;
      }

      // Write the HTML content
      printWindow.document.write(html);
      printWindow.document.close();

      // Wait for content to load
      printWindow.onload = () => {
        // Focus the window and trigger print
        printWindow.focus();
        printWindow.print();
        
        // Close the window after a short delay
        setTimeout(() => {
          printWindow.close();
          resolve();
        }, 1000);
      };

      // Handle errors
      printWindow.onerror = () => {
        printWindow.close();
        reject(new Error('Failed to load content for printing'));
      };

    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Download HTML as text file (fallback method)
 */
export function downloadAsText(html: string, filename: string = 'travel-brief.txt'): void {
  try {
    // Create a temporary div to extract text content
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = html;
    const textContent = tempDiv.textContent || tempDiv.innerText || '';

    // Create and download the file
    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.style.display = 'none';
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Failed to download as text:', error);
    throw error;
  }
}

/**
 * Open HTML in new window for viewing
 */
export function openInNewWindow(html: string, title: string = 'Travel Brief'): void {
  try {
    const newWindow = window.open('', '_blank');
    
    if (!newWindow) {
      throw new Error('Could not open new window. Please allow popups for this site.');
    }

    newWindow.document.write(html);
    newWindow.document.title = title;
    newWindow.document.close();
    
    // Focus the new window
    newWindow.focus();
  } catch (error) {
    console.error('Failed to open in new window:', error);
    throw error;
  }
}

/**
 * Generate PDF using a professional PDF service (if available)
 * This would integrate with services like PDFShift, Puppeteer, etc.
 */
export async function generatePDFWithService(
  html: string, 
  filename: string = 'travel-brief.pdf',
  serviceUrl?: string
): Promise<Blob | null> {
  
  if (!serviceUrl) {
    // No service configured, fallback to print method
    await generatePDFWithPrint(html, filename);
    return null;
  }

  try {
    const response = await fetch(serviceUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        html: html,
        filename: filename,
        options: {
          format: 'A4',
          margin: {
            top: '20mm',
            right: '20mm',
            bottom: '20mm',
            left: '20mm'
          },
          printBackground: true,
          displayHeaderFooter: true,
          headerTemplate: '<div style="font-size: 10px; text-align: center; width: 100%;">Travel Brief AI</div>',
          footerTemplate: '<div style="font-size: 10px; text-align: center; width: 100%;">Generated by TravelBrief.ai</div>'
        }
      })
    });

    if (!response.ok) {
      throw new Error(`PDF service error: ${response.statusText}`);
    }

    return await response.blob();
  } catch (error) {
    console.error('PDF service failed, falling back to print method:', error);
    await generatePDFWithPrint(html, filename);
    return null;
  }
}

/**
 * Enhanced HTML template for better PDF generation
 */
export function enhanceHTMLForPDF(html: string): string {
  // Add PDF-specific styles
  const pdfStyles = `
    <style>
      @media print {
        body {
          -webkit-print-color-adjust: exact !important;
          color-adjust: exact !important;
          print-color-adjust: exact !important;
          background-color: #ffffff !important;
        }
        
        .container {
          max-width: none !important;
          margin: 0 !important;
          padding: 20px !important;
          box-shadow: none !important;
          background-color: #ffffff !important;
        }
        
        /* Prevent content from being cut between pages */
        p, h1, h2, h3, h4, h5, h6, ul, ol, li, blockquote, table, tr {
          page-break-inside: avoid !important;
          break-inside: avoid !important;
        }
        
        /* Force page breaks before major sections */
        .day-section {
          page-break-before: always !important;
          break-before: always !important;
        }
        
        /* First day section should not have a page break */
        .day-section:first-child {
          page-break-before: auto !important;
          break-before: auto !important;
        }
        
        .header {
          break-inside: avoid !important;
          page-break-inside: avoid !important;
          background: linear-gradient(135deg, #4f46e5 0%, #3b82f6 100%) !important;
          color: white !important;
          padding: 30px !important;
          border-radius: 12px !important;
          margin-bottom: 20px !important;
        }
        
        .content-section {
          break-inside: avoid !important;
          page-break-inside: avoid !important;
          margin-bottom: 30px !important;
          background-color: #f8fafc !important;
          border-radius: 10px !important;
          padding: 20px !important;
          border-left: 5px solid #3b82f6 !important;
        }
        
        .trip-summary {
          break-inside: avoid !important;
          page-break-inside: avoid !important;
          background: linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%) !important;
          padding: 25px !important;
          border-radius: 10px !important;
          margin-bottom: 30px !important;
          border: 1px solid #bae6fd !important;
        }
        
        .footer {
          break-inside: avoid !important;
          page-break-inside: avoid !important;
          background: linear-gradient(135deg, #4f46e5 0%, #3b82f6 100%) !important;
          color: white !important;
          padding: 20px !important;
          border-radius: 12px !important;
          margin-top: 30px !important;
        }
        
        /* Colorful section headers */
        .section-title, .content-section h2 {
          background: linear-gradient(90deg, #3b82f6 0%, #2563eb 100%) !important;
          color: white !important;
          padding: 12px 20px !important;
          border-radius: 8px !important;
          margin-bottom: 15px !important;
          font-weight: bold !important;
        }
        
        /* Day sections with colorful styling */
        .day-section {
          background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%) !important;
          border: 1px solid #e2e8f0 !important;
          border-radius: 12px !important;
          padding: 25px !important;
          margin-bottom: 30px !important;
          box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05) !important;
          position: relative !important;
          overflow: hidden !important;
        }
        
        .day-section::before {
          content: '' !important;
          position: absolute !important;
          top: 0 !important;
          left: 0 !important;
          right: 0 !important;
          height: 6px !important;
          background: linear-gradient(90deg, #10b981 0%, #059669 100%) !important;
        }
        
        /* Colorful typography */
        body {
          font-size: 12pt !important;
          line-height: 1.6 !important;
          color: #1f2937 !important;
        }
        
        h1 { 
          font-size: 24pt !important;
          color: #1e40af !important;
          margin-bottom: 15px !important;
        }
        
        h2 { 
          font-size: 20pt !important;
          color: #1d4ed8 !important;
          margin-bottom: 12px !important;
        }
        
        h3 { 
          font-size: 16pt !important;
          color: #2563eb !important;
          margin-bottom: 10px !important;
        }
        
        h4 { 
          font-size: 14pt !important;
          color: #3b82f6 !important;
          margin-bottom: 8px !important;
        }
        
        /* Colorful blockquotes */
        blockquote {
          background: linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%) !important;
          border-left: 5px solid #10b981 !important;
          padding: 15px 20px !important;
          margin: 20px 0 !important;
          border-radius: 8px !important;
          color: #065f46 !important;
        }
        
        /* Colorful lists */
        ul, ol {
          padding-left: 25px !important;
          margin: 15px 0 !important;
        }
        
        li {
          margin-bottom: 8px !important;
          color: #374151 !important;
        }
        
        /* Colorful tables */
        table {
          width: 100% !important;
          border-collapse: collapse !important;
          margin: 20px 0 !important;
          background: white !important;
          border-radius: 8px !important;
          overflow: hidden !important;
          border: 1px solid #e5e7eb !important;
        }
        
        th {
          background: #3b82f6 !important;
          color: white !important;
          padding: 12px !important;
          text-align: left !important;
        }
        
        td {
          padding: 12px !important;
          border-top: 1px solid #e5e7eb !important;
        }
        
        tr:nth-child(even) {
          background: #f9fafb !important;
        }
      }
    </style>
  `;

  // Insert styles before closing head tag
  return html.replace('</head>', pdfStyles + '</head>');
}